### ISSUE TITLE
Problematic Wallets - Ethereum

### ISSUE THREAD

**Issue by jonesmac** [XYOracleNetwork/sdk-xyo-client-js#962]
http://localhost:3000/web3/nfts/?address=0xE0036fb4B5A3B232aCfC01fEc3bD1D787a93da75&chainId=1

[Block explorer](https://etherscan.io/address/0xE0036fb4B5A3B232aCfC01fEc3bD1D787a93da75)

Error:

```
{
    "message": "undefined is not a valid TokenType",
    "name": "CryptoWalletNftWitness",
    "query": "network.xyo.boundwitness",
    "schema": "network.xyo.error.module",
    "sources": [
        "3e0ef68a9be838e966f52ce92615d661d094c75cf7e5ae9aa3a675d5fdcb5501"
    ]
}
```

**Comment by arietrouw** [comment]
0xE0036fb4B5A3B232aCfC01fEc3bD1D787a93da75

**Comment by jonesmac** [comment]
found by @jordantrouw 

I believe its supposed to load as a collection but seems to error out as a wallet.
0xe6932D364De93723da51630568442FCeA6D7cfA7

https://opensea.io/B33LOn

**Comment by arietrouw** [comment]
The reason this is failing is that the witness returns an empty list which the boundwitness then rejects.  A witness should at least return the info about the wallet.

**Comment by arietrouw** [comment]
Fixed errors.
But now the site needs to handle an undefined coming back when address not found.

**Comment by arietrouw** [comment]
Note: Will need new deploy of server or running locally to prevent the witness error

**Comment by arietrouw** [comment]
This should be fixed with empty wallet witness fix.  Need to verify in UI that it no longer happens with latest SDK (2.75.8+)

**Comment by jonesmac** [comment]
@arietrouw I'm still seeing the same error with sdk v2.75.8 

Test page - http://localhost:3000/web3/nfts/?address=0xE0036fb4B5A3B232aCfC01fEc3bD1D787a93da75&chainId=1

returns: 

{
    "message": "undefined is not a valid TokenType",
    "name": "CryptoWalletNftWitness",
    "query": "network.xyo.boundwitness",
    "schema": "network.xyo.error.module",
    "sources": [
        "1d35094321b4b82ff28d1bfa67c7aa1aaedb341e3dedf5c5e2d2ad2c320e13f2"
    ]
}

**Comment by arietrouw** [comment]
Infura returns undefined for some NFTs.  Updated type toTokenType to return null in that case

Client SDK 2.75.15+
